version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  discord: antonioned/discord@0.1.0
  gitops: shibataka000/gitops@0.0.1

jobs:
  build-test-and-publish-docker-image:
    docker:
      - image: circleci/golang:1.15-browsers
    working_directory: /go/src/github.com/xavicampa/xavic-test
    steps:
      - checkout
      - run: make
      - run: mkdir test-results
      - run: gotestsum --junitfile test-results/unit-tests.xml     
      - store_test_results:
          path: test-results 
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/update-description:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME      
      - discord/status
  
  update_manifests:
    docker:
      - image: ubuntu
    steps:
      - run: apt update && apt install snapd -y && snap install kustomize
      # - run: kustomize build
      # - gitops/clone-repository:
      #     repo: xavicampa/xavic-test-manifests
      # - gitops/update-image:
      #     current-image-name: xavic-test
      #     new-image-name: xavic-test
      #     new-image-tag: $CIRCLE_SHA1
      #     path: kubernetes

workflows:
  build:-and-publish-docker-image:
    jobs:
      # - build-test-and-publish-docker-image
      - update_manifests
          # requires:
            # - build-test-and-publish-docker-image