version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  discord: antonioned/discord@0.1.0

jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/update-description:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - discord/status:
          fail_only: false
          success_message: "**${CIRCLE_USERNAME}**'s **${CIRCLE_JOB}** build successfull: **${CIRCLE_BUILD_URL}**."
          failure_message: "**${CIRCLE_USERNAME}**'s **${CIRCLE_JOB}** build failed: **${CIRCLE_BUILD_URL}**."
          webhook: "${DISCORD_STATUS_WEBHOOK}"

workflows:
  build-docker-image-and-notify:
    jobs:
      - build
      
    

# jobs:
#   build:
#     docker:
#       - image: circleci/golang:1.15-browsers
#     working_directory: /go/src/github.com/xavicampa/xavic-test
#     steps:
#       - checkout
#       - run: make
#       - store_artifacts:
#           path: bin/main