version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  discord: antonioned/discord@0.1.0

jobs:
  build-and-publish-docker-image:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/update-description:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - discord/status

workflows:
  build-and-publish-docker-image:
    jobs:
      - build-and-publish-docker-image