# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  docker: circleci/docker@1.5.0

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true

# jobs:
#   build:
#     docker:
#       - image: circleci/golang:1.15-browsers
#     working_directory: /go/src/github.com/xavicampa/xavic-test
#     steps:
#       - checkout
#       - run: make
#       - store_artifacts:
#           path: bin/main