on: [push]

jobs:
  api_audit_job:
    runs-on: ubuntu-latest
    name: Audit OpenAPI files
    steps:
    - uses: actions/checkout@v2
    - uses: 42Crunch/api-security-audit-action@v1
      with:
        # Please create free account at https://platform.42crunch.com/register
        # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
        api-token: ${{ secrets.API_TOKEN }}
        min-score: 85
